name: nextcloud-client
version: master-branch
icon: theme/colored/Nextcloud-icon.svg
summary: Nextcloud Desktop Client
description: |
  The Nextcloud Desktop Client is a tool to synchronize files from Nextcloud
  Server with your computer.

grade: stable
confinement: strict
base: core18

parts:
  client:
    plugin: cmake
    source: .
    source-type: git
    #source-subdir: client
    build-packages:
      - g++
      - libsqlite3-dev
      - libssl-dev
      - libqt5webkit5-dev
      - pkg-config
      - qt5keychain-dev
      - qttools5-dev-tools
      - libzip-dev
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - cmake
    stage-packages:
      - sqlite3
      # qtkeychain requires these libs at runtime to support keyrings
      - libsecret-1-0
      - libgnome-keyring0
    configflags:
      - -DNO_SHIBBOLETH=1
      - -DCMAKE_BUILD_TYPE=Release
      - -DOEM_THEME_DIR=$SNAPCRAFT_PART_INSTALL/../src/nextcloudtheme
        #- -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_INSTALL_LIBDIR=/usr/lib
      - -DSYSCONF_INSTALL_DIR=/etc
        #install: |
        #    override-build:
      # Replace icon with the correct path in the snap
      #sed -ri "s|(^Icon=).*$|\1\${SNAP}/meta/gui/icon.svg|" "$SNAPCRAFT_PART_INSTALL/usr/share/applications/nextcloud.desktop"

    after:
      - desktop-qt5
      - snapcraft-preload

  xdg-open:
    source: https://github.com/ubuntu-core/snapd-xdg-open.git
    source-depth: 1
    plugin: dump
    organize:
      data/xdg-open: bin/xdg-open
    prime:
      - bin

apps:
  nextcloud-client:
    aliases:
      - nextcloud

    command: snapcraft-preload nextcloud
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/nextcloud:$LD_LIBRARY_PATH
    desktop: usr/share/applications/nextcloud.desktop
    plugs:
      - unity7
      - home
      - network
      - network-bind
      - network-manager
      - password-manager-service

  cmd:
    aliases:
      - nextcloudcmd
    command: snapcraft-preload nextcloudcmd
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/nextcloud:$LD_LIBRARY_PATH
    plugs:
      - unity7
      - home
      - network
