name: nextcloud-client
version: 2.5.0-beta2
icon: theme/colored/Nextcloud-icon.svg
summary: Nextcloud Desktop Client
description: |
  The Nextcloud Desktop Client is a tool to synchronize files from Nextcloud
  Server with your computer.

grade: stable
confinement: strict
base: core18

parts:
  client:
    plugin: cmake
    source: .
    source-type: git
    source-tag: v2.5.0-beta2
    #source-subdir: client
    build-packages:
      - g++
      - libsqlite3-dev
      - libssl-dev
      - libqt5webkit5-dev
      - pkg-config
      - qt5keychain-dev
      - qttools5-dev-tools
      - libzip-dev
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - qtwebengine5-dev
      - qttools5-dev
      - extra-cmake-modules
    stage-packages:
      - sqlite3
      - qtwayland5
      - libqt5xml5
      # qtkeychain requires these libs at runtime to support keyrings
      - libsecret-1-0
      - libgnome-keyring0
    configflags:
      - -DNO_SHIBBOLETH=1
      - -DCMAKE_BUILD_TYPE=Debug
        #- -DOEM_THEME_DIR=$SNAPCRAFT_PART_INSTALL/../src/nextcloudtheme
        #- -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_INSTALL_LIBDIR=/usr
        #- -DSYSCONF_INSTALL_DIR=/etc
        #install: |
        #    override-build:
      # Replace icon with the correct path in the snap
      #sed -ri "s|(^Icon=).*$|\1\${SNAP}/meta/gui/icon.svg|" "$SNAPCRAFT_PART_INSTALL/usr/share/applications/nextcloud.desktop"

    after:
      - desktop-qt5
      #- snapcraft-preload

apps:
  nextcloud-client:
    aliases:
      - nextcloud

    command: desktop-launch nextcloud
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/nextcloud:$LD_LIBRARY_PATH
      #desktop: usr/share/applications/nextcloud.desktop
      DISABLE_WAYLAND: 1
    plugs:
      - unity7
      - home
      - network
      - network-bind
      - network-manager
      - password-manager-service
      - desktop
      - wayland
      - desktop-legacy
      - opengl
      - x11
      - system-observe

  cmd:
    aliases:
      - nextcloudcmd
    command: nextcloudcmd
    environment:
        LD_LIBRARY_PATH: $SNAP/usr/lib/nextcloud:$LD_LIBRARY_PATH
    plugs:
      - unity7
      - home
      - network
